name: Test
on: push
jobs:
  Job1:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Initialize
      run: |
        mkdir BuildResults
        mkdir BuildResults\TestBench-Release
        dotnet add Test package -v 4.4.6 ReportGenerator
    - name: Build library
      run: |
        dotnet msbuild -nologo -restore -p:Configuration=Release Sequences
        dotnet msbuild -nologo -restore -p:Configuration=Release Test
        copy Sequences\bin\Release\*.nupkg BuildResults\TestBench-Release
    - name: Build coverage suite
        dotnet msbuild -nologo -restore -p:Configuration=Release Test
    - name: Run coverage suite
      run: |
      dotnet test -c Release -p:CollectCoverage=true -p:CoverletOutputFormat=lcov -p:CoverletOutput=TestResults\lcov Test
    - name: Generate coverage report
      run: dotnet "%USERPROFILE%\.nuget\packages\reportgenerator\4.4.6\tools\netcoreapp3.0\ReportGenerator.dll" -reports:Test\TestResults\lcov.info -targetdir:TestResults\TestBench-CoverageReport
    - uses: actions/upload-artifact@v1
      with:
        name: RunnerOutput-Release
        path: BuildResults\TestBench-Release
