name: Test
on: push
jobs:
  Job1:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Initialize
      run: mkdir TestResults
    - name: Build library
      run: |
        dotnet msbuild -nologo -restore -p:Configuration=Debug TestBench
        copy TestBench\bin\Debug\*.nupkg TestResults\
    - name: Build standard suite
      run: dotnet msbuild -nologo -restore -p:Configuration=Debug Test
    - name: Run standard suite
      run: dotnet test -c Debug Test
    - uses: actions/upload-artifact@v1
      with:
        name: TestBench-Test
        path: TestResults
