name: Test
on: push
jobs:
  Job1:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Initialize
      run: |
        mkdir BuildResults
        mkdir BuildResults\TestBench-Debug
    - name: Build library
      run: |
        dotnet msbuild -nologo -restore -p:Configuration=Debug TestBench
        copy TestBench\bin\Debug\*.nupkg BuildResults\TestBench-Debug
    - name: Build standard suite
      run: |
        dotnet restore TestCore
        dotnet msbuild -nologo -p:Configuration=Debug TestCore
    - name: Run standard suite
      run: dotnet test -c Debug TestCore
    - uses: actions/upload-artifact@v1
      with:
        name: RunnerOutput-Debug
        path: BuildResults\TestBench-Debug
